//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadaniaWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksHistory
    {
        public int tsh_id { get; set; }
        public int tsh_TaskId { get; set; }
        public Nullable<System.DateTime> tsh_EventDate { get; set; }
        public int tsh_EventType { get; set; }
    
        public virtual DictTaskEventType DictTaskEventType { get; set; }
        public virtual Task Task { get; set; }
    }
}
